site_name: DJ Knowledge Base

plugins:
    #- search
    #- mkpdfs

theme:
    #name: readthedocs
    #name: mkdocs

    #name: rtd-dropdown
    name: material
    features:
      # - navigation.instant
      #- navigation.sections
      #- navigation.tabs

markdown_extensions:
    # this makes anchors at the headings
    - toc:
        permalink: yes
    - admonition
    - def_list
    #- mdx_gh_links:
    #    user: mkdocs
    #    repo: mkdocs
        
    
# cat index.md  | grep -- "^# "  | awk -F, '{print "-",$1,":",$1".md" }'    
# for file in `grep_onoff.sh ../mkdocs.yml nav | grep md | columnx.sh -1` ; do  touch "$file" ; done
nav:
  - About :
    - About this KB : about.md
    - DJ Census : dj_census.md
    - DJ Hall of Fame : dj_hall_of_fame.md
    
  - Traktor:
    - OS-Folders organization : os_folders.md
    - Traktor Features : traktor.md
    - Traktor Elastic Beatgrids : traktor_elastic_beatgrids.md
    - Traktor Slow preferences Window : traktor_slow_prefs.md
    - Trakor Sound Quality : sound_quality.md

  - Mappings & Controllers:
    - Free Mappings : free_mappings.md
    - BOME mappings migration : bome_mappings.md
    - Mappings Tutorials : mapping_tutorials.md
    - Hardware Controllers : hardware_controllers.md
    
  - DJ Info:
    - DJ Tutorials : dj_tutorials.md
    - Effects : effects.md
    - DJ Reviews : reviews.md
    - DJ Information sources : dj_info_sources.md
    - Music Styles : music_style.md
    
  - Multiple DJ Softwares:
    - DJ collection converters : dj_collection_converters.md
    - Rekordbox v6 topics : rekordbox_v6.md
    - MIXXX topics : mixxx.md
    
  - Tools & Optimization:
    - Free DJ Software Tools : free_dj_tools.md
    - DJ Software optimization : dj_optimization.md
    - Windows usage : windows.md

    
    
    
  
  
# Target for Edit in GitHub button.
#repo_url: https://github.com/MichaelCurrin/mkdocs-quickstart/  
    
